version: "3.3"

services:

  site:
    image: docsy/docsy-example
    container_name: docsy
    restart: unless-stopped
    build:
      context: .
    command: server
    network_mode: host
    volumes:
      - .:/src
