version: "3.3"

services:

  site:
    image: docsy/docsy-example
    container_name: docsy
    restart: unless-stopped
    command: server -b https://docs.yiqia.com --appendPort=false
    environment:
      HUGO_ENV: production
    build:
      context: .
    network_mode: host
    volumes:
      - .:/src
